Don't build qtscript when stl isn't available
Task-number: QTBUG-7813

Change-Id: Ie0873e7fbd1168b11e5881d156a0583d0fa7f859
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@nokia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7509,6 +7509,7 @@ fi
 #
 canBuildQtXmlPatterns="yes"
 canBuildWebKit="$HAVE_STL"
+canBuildQtScript="$HAVE_STL"
 canBuildQtConcurrent="yes"
 
 # WebKit requires stdint.h
@@ -7700,8 +7701,13 @@ else
     QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_WEBKIT"
 fi
 
+if [ "$CFG_SCRIPT" = "yes" -a "$canBuildQtScript" = "no" ]; then
+    echo "Error: QtScript was requested, but it can't be built on this platform."
+    exit 1
+fi
+
 if [ "$CFG_SCRIPT" = "auto" ]; then
-    CFG_SCRIPT="yes"
+    CFG_SCRIPT="$canBuildQtScript"
 fi
 
 if [ "$CFG_SCRIPT" = "yes" ]; then
