Disable debug-only framework builds on Mac.
("Fixes" WebKit build error with ./configure -debug)

This puts the build system in an inconsistent state: We
configure for debug only but still build both debug and 
release binaries. Use -no-framework of you want a pure
debug build.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7968,8 +7968,10 @@ if [ "$CFG_OPENSSL" = "linked" ] && [ "$OPENSSL_LIBS" = "" ]; then
 fi
 if [ "$PLATFORM_MAC" = "yes" ] && [ "$CFG_FRAMEWORK" = "yes" ] && [ "$CFG_DEBUG" = "yes" ] && [ "$CFG_DEBUG_RELEASE" = "no" ]; then
     echo
-    echo "NOTE: Mac OS X frameworks implicitly build debug and release Qt libraries."
+    echo "Error: debug-only framework builds are not supported. Configure with -no-framework"
+    echo "if you want a pure debug build."
     echo
+    exit 1
 fi
 
 sepath=`echo "$relpath" | sed -e 's/\\./\\\\./g'`
